

class TestPipelineCount:
    def test_gid_210419_get_has_issue_pipeline_run_count(self):
        """
        Description:
            Verify ACS provides an API endpoint to get count of "Has Issue" pipeline runs
        Prerequisites:
            ...
        Test Data:
            ...
        Steps:
            1) ...
                ER: ...
                Notes: ...
            2) ...
            3) ...
            4) ...
            5) ...
            6) ...
        Projects: ...
        """
        # code
        pass
